services:
  nginx:
    image: nginx:1.23.4
    restart: ${RESTART}
    depends_on:
      - php
      - db
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.port=443"
      - "traefik.http.routers.${PROJECT}.rule=Host(`${APP_DOMAIN}`, `${API_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT}.tls=true"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app:delegated

  php:
    build:
      context: ./docker/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    restart: ${RESTART}
    networks:
      - web
      - default
    volumes:
      - .:/app
    depends_on:
      - db
      - node
    links:
      - db
      - node

  node:
    image: node:19.9.0
    environment:
      NODE_ENV: development
    working_dir: /app
    networks:
      - web
      - default
    volumes:
      - .:/app

  db:
    image: postgres:15.2
    restart: ${RESTART}
    networks:
      - web
      - default
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

networks:
  web:
    external: true

volumes:
  db:
