services:
  nginx:
    image: nginx:1.23.4
    restart: ${RESTART}
    depends_on:
      - php
      - db
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT}.rule=Host(`${APP_DOMAIN}`) || Host(`${API_DOMAIN}`)"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app:delegated

  php:
    build:
      context: ./docker/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    restart: ${RESTART}
    environment:
      PHP_ENABLE_XDEBUG: 1
      PHP_IDE_CONFIG: "serverName=xdebug"
    networks:
      - web
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/base.ini
      - ./docker/php/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
      - node
    links:
      - db
      - node
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node:
    image: node:22.3.0
    environment:
      NODE_ENV: development
    restart: ${RESTART}
    working_dir: /app
    networks:
      - web
    volumes:
      - .:/app
    ports:
      - '5173:5173'
    command: 'npm run dev'

  db:
    image: postgres:15.2
    restart: ${RESTART}
    networks:
      - web
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data

networks:
  web:
    external: true

volumes:
  db:
